### ISSUE TITLE
Wrong line endings (?)

### ISSUE THREAD

**Issue by cbenz** [jsongraph/jgf-dot#2]
Sorry but it seems that the line encodings are wrong on the `cli.js` packaged script:

```
$ jgfdot
/usr/bin/env: ‘node\r’: No such file or directory
```

If I run `dos2unix` as suggested by this [StackOverflow answer](http://stackoverflow.com/a/30349952/3548266), it's OK:

```
$ sudo dos2unix  /usr/lib/node_modules/jgf-dot/bin/cli.js
$ jgfdot
[waiting for input...]
```

That's strange, because if I run the client on the last commit on `master`, it's OK.

Could you check and re-release? :)

**Comment by RangerMauve** [comment]
This is out in 1.1.1
