### ISSUE TITLE
1.1.1 version

### ISSUE THREAD

**Issue by abargnesi** [jsongraph/jgf-dot#4]
Here is what will be going in a 1.1.1 update.

@RangerMauve Can you add me a contributor on npm (user: **abargnesi**)?

### Added
- Docker build file to simplify command execution ([Issue #3][3]).
  - [Ben Tucker][Ben Tucker]

### Fixed
- Republish to npm to fix line-ending issue ([Issue #2][2]).
  - [Tony Bargnesi][Tony Bargnesi]

[1.1.1]:         https://github.com/jsongraph/jgf-dot/compare/5c17bf...1.1.1
[2]:             https://github.com/jsongraph/jgf-dot/issues/2
[3]:             https://github.com/jsongraph/jgf-dot/issues/3
[Ben Tucker]:    https://github.com/bjtucker
[Tony Bargnesi]: https://github.com/abargnesi

**Comment by RangerMauve** [comment]
Done! Sorry for the delay.

**Comment by RangerMauve** [comment]
Released it for yah
