### ISSUE TITLE
Error: "``: No such file or directory`" when executing the program from the command line

### ISSUE THREAD

**Issue by n-eq** [jsongraph/jgf-dot#5]
Hi,

I get the error mentioned in the title when trying to execute the program on a JSON file:
`: No such file or directory`
Everything is normally installed, jgf-dot, graphviz (but that's not important for the moment). 
I tried both commands (with a cat/pipe and with i/o redirection).
Can anyone help?

**Comment by RangerMauve** [comment]
Can you paste the exact commands you ran, what your folder structure looks like, and what version of the tool you have installed?

Thanks

**Comment by n-eq** [comment]
I may actually be missing something during the installation.
Here's what I've come accross so far:
1) Followed the installation instructions from command line in README
=> It appears to be installing properly `jgf-dot@1.1.0` at the end.
2) I run `jgfdot` (oddly enough there isn't `jgd-dot`), and I get the error mentioned previously. Even the command `jgfdot --help` produces the same error.
Thanks.

**Comment by RangerMauve** [comment]
I'm pretty sure there's no help command implemented (haven't looked at this since I made it ages ago). It might be related to #2. I'll go get that published and we'll see if that helps

**Comment by RangerMauve** [comment]
Try installing 1.1.1, and see if that fixes things

**Comment by n-eq** [comment]
How can I specify the version to install? Provided that I installed the program via `npm`.

**Comment by RangerMauve** [comment]
`npm install -g jgf-dot@1.1.1`

**Comment by RangerMauve** [comment]
Make sure you specify a file for it to open

**Comment by n-eq** [comment]
I successfully installed the program as suggested.
Now, I get the following error when executing the program on a json file (I was wondering if I shoud open a new issue):
```sh
$ jgfdot /usr/share/npm/package.json
/usr/local/lib/node_modules/jgf-dot/node_modules/graphlib-json-graph/index.js:19
	throw new TypeError("No graphs defined");
	^

TypeError: No graphs defined
    at toGraph (/usr/local/lib/node_modules/jgf-dot/node_modules/graphlib-json-graph/index.js:19:8)
    at toDot (/usr/local/lib/node_modules/jgf-dot/index.js:7:22)
    at /usr/local/lib/node_modules/jgf-dot/bin/cli.js:9:24
    at Gatherer.<anonymous> (/usr/local/lib/node_modules/jgf-dot/node_modules/gather-stream/index.js:41:5)
    at emitNone (events.js:91:20)
    at Gatherer.emit (events.js:185:7)
    at finishMaybe (_stream_writable.js:515:14)
    at endWritable (_stream_writable.js:525:3)
    at Gatherer.Writable.end (_stream_writable.js:490:5)
    at ReadStream.onend (_stream_readable.js:511:10)
```

**Comment by RangerMauve** [comment]
I think the error is pretty self-explanatory. You tried to open a JSON file that doesn't contain JGF graphs. Thus "no graphs defined"

**Comment by RangerMauve** [comment]
Try using the example graph that's provided in the repo: https://github.com/jsongraph/jgf-dot/blob/master/example/graph.json

**Comment by n-eq** [comment]
It worked finally, thanks for your help @RangerMauve !

**Comment by RangerMauve** [comment]
No problem! Hopefully this tool proves useful. 😄
